# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.14
default_stages: [pre-commit]
repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-shebang-scripts-are-executable
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-toml
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-check
        name: ruff-unused-imports
        args: [--select, F401, --fix]
    -   id: ruff-format
